import type { Product } from "@/components/ui/product-card"
import type { Article } from "@/components/ui/article-card"

// Mock product data
export const mockProducts: Record<string, Product[]> = {
  iphone: [
    {
      id: "1",
      name: "iPhone 17 Pro Max 256GB Chính Hãng",
      slug: "iphone-17-pro-max-256gb",
      image: "/placeholder.svg?height=300&width=300",
      price: 36990000,
      originalPrice: 38990000,
      discount: 5,
      rating: 4.5,
      installment: true,
      gifts: ["Ốp lưng", "Cường lực"],
    },
    {
      id: "2",
      name: "iPhone 17 Pro Max 128GB Chính Hãng",
      slug: "iphone-17-pro-max-128gb",
      image: "/placeholder.svg?height=300&width=300",
      price: 30990000,
      originalPrice: 31990000,
      discount: 3,
      rating: 4.8,
      installment: true,
    },
    {
      id: "3",
      name: "iPhone 17 Pro 256GB Chính Hãng",
      slug: "iphone-17-pro-256gb",
      image: "/placeholder.svg?height=300&width=300",
      price: 24490000,
      originalPrice: 25990000,
      discount: 6,
      rating: 4.6,
      installment: true,
      gifts: ["Sạc nhanh 20W"],
    },
    {
      id: "4",
      name: "iPhone 17 Pro Max 512GB Chính Hãng",
      slug: "iphone-17-pro-max-512gb",
      image: "/placeholder.svg?height=300&width=300",
      price: 33900000,
      originalPrice: 35900000,
      discount: 6,
      rating: 4.7,
      installment: true,
    },
    {
      id: "5",
      name: "iPhone 17 Pro Max 1TB Chính Hãng",
      slug: "iphone-17-pro-max-1tb",
      image: "/placeholder.svg?height=300&width=300",
      price: 25400000,
      originalPrice: 26400000,
      discount: 4,
      rating: 4.5,
      installment: true,
    },
  ],
  samsung: [
    {
      id: "6",
      name: "Samsung Galaxy Z Fold 7 Ultra 256GB Chính Hãng",
      slug: "samsung-galaxy-z-fold-7",
      image: "/placeholder.svg?height=300&width=300",
      price: 38990000,
      originalPrice: 46990000,
      discount: 17,
      rating: 4.6,
      installment: true,
      gifts: ["Bao da", "Bút S-Pen"],
    },
    {
      id: "7",
      name: "Samsung Galaxy S25 Ultra 256GB Chính Hãng",
      slug: "samsung-galaxy-s25-ultra",
      image: "/placeholder.svg?height=300&width=300",
      price: 25490000,
      originalPrice: 28990000,
      discount: 12,
      rating: 4.7,
      installment: true,
    },
    {
      id: "8",
      name: "Samsung Galaxy S25 128GB Chính Hãng",
      slug: "samsung-galaxy-s25",
      image: "/placeholder.svg?height=300&width=300",
      price: 12890000,
      originalPrice: 14990000,
      discount: 14,
      rating: 4.4,
      installment: true,
    },
    {
      id: "9",
      name: "iPhone 17 Pro Max 256GB Chính Hãng",
      slug: "iphone-17-pro-max-256gb-2",
      image: "/placeholder.svg?height=300&width=300",
      price: 23700000,
      originalPrice: 26000000,
      discount: 9,
      rating: 4.5,
      installment: true,
    },
    {
      id: "10",
      name: "Samsung Galaxy A47 5G Chính Hãng",
      slug: "samsung-galaxy-a47",
      image: "/placeholder.svg?height=300&width=300",
      price: 5490000,
      originalPrice: 6490000,
      discount: 15,
      rating: 4.3,
      installment: true,
    },
  ],
  xiaomi: [
    {
      id: "11",
      name: "Xiaomi Redmi Note 15 Pro+ 5G Chính Hãng",
      slug: "xiaomi-redmi-note-15-pro",
      image: "/placeholder.svg?height=300&width=300",
      price: 5590000,
      originalPrice: 6590000,
      discount: 15,
      rating: 4.4,
      installment: true,
    },
    {
      id: "12",
      name: "OPPO Reno13 F 5G Chính Hãng",
      slug: "oppo-reno13-f-5g",
      image: "/placeholder.svg?height=300&width=300",
      price: 11690000,
      originalPrice: 12990000,
      discount: 10,
      rating: 4.3,
      installment: true,
    },
    {
      id: "13",
      name: "Xiaomi T2 5G Chính Hãng",
      slug: "xiaomi-t2-5g",
      image: "/placeholder.svg?height=300&width=300",
      price: 13290000,
      originalPrice: 14990000,
      discount: 11,
      rating: 4.5,
      installment: true,
    },
    {
      id: "14",
      name: "Xiaomi Redmi 15C 128GB Chính Hãng",
      slug: "xiaomi-redmi-15c",
      image: "/placeholder.svg?height=300&width=300",
      price: 3090000,
      originalPrice: 3590000,
      discount: 14,
      rating: 4.2,
      installment: true,
    },
    {
      id: "15",
      name: "OPPO A5 Pro 256GB Chính Hãng",
      slug: "oppo-a5-pro",
      image: "/placeholder.svg?height=300&width=300",
      price: 7990000,
      originalPrice: 8990000,
      discount: 11,
      rating: 4.4,
      installment: true,
    },
  ],
  tablet: [
    {
      id: "16",
      name: "Samsung Galaxy Tab S10 5G 128GB",
      slug: "samsung-galaxy-tab-s10",
      image: "/placeholder.svg?height=300&width=300",
      price: 8990000,
      originalPrice: 10990000,
      discount: 18,
      rating: 4.6,
      installment: true,
    },
    {
      id: "17",
      name: "MacBook Air M3 13 inch 256GB",
      slug: "macbook-air-m3",
      image: "/placeholder.svg?height=300&width=300",
      price: 25990000,
      originalPrice: 27990000,
      discount: 7,
      rating: 4.8,
      installment: true,
    },
    {
      id: "18",
      name: "iPad air M3 11 inch Wifi 128GB",
      slug: "ipad-air-m3",
      image: "/placeholder.svg?height=300&width=300",
      price: 14900000,
      originalPrice: 16990000,
      discount: 12,
      rating: 4.7,
      installment: true,
    },
    {
      id: "19",
      name: "HUAWEI Matebook X 5",
      slug: "huawei-matebook-x5",
      image: "/placeholder.svg?height=300&width=300",
      price: 14490000,
      originalPrice: 15990000,
      discount: 9,
      rating: 4.5,
      installment: true,
    },
    {
      id: "20",
      name: "Xiaomi Pad 7 Pro 2 Chính Hãng",
      slug: "xiaomi-pad-7-pro",
      image: "/placeholder.svg?height=300&width=300",
      price: 9480000,
      originalPrice: 10980000,
      discount: 14,
      rating: 4.4,
      installment: true,
    },
  ],
  watch: [
    {
      id: "21",
      name: "Apple Watch Series 9 41mm Nhôm",
      slug: "apple-watch-series-9",
      image: "/placeholder.svg?height=300&width=300",
      price: 11400000,
      originalPrice: 12900000,
      discount: 12,
      rating: 4.7,
      installment: true,
    },
    {
      id: "22",
      name: "HUAWEI Watch GT 5 Pro",
      slug: "huawei-watch-gt5-pro",
      image: "/placeholder.svg?height=300&width=300",
      price: 6590000,
      originalPrice: 7490000,
      discount: 12,
      rating: 4.5,
      installment: true,
    },
    {
      id: "23",
      name: "Samsung Galaxy Watch8 Chính Hãng",
      slug: "samsung-galaxy-watch8",
      image: "/placeholder.svg?height=300&width=300",
      price: 7790000,
      originalPrice: 8990000,
      discount: 13,
      rating: 4.6,
      installment: true,
    },
    {
      id: "24",
      name: "HUAWEI Watch D7 B",
      slug: "huawei-watch-d7",
      image: "/placeholder.svg?height=300&width=300",
      price: 3790000,
      originalPrice: 4290000,
      discount: 12,
      rating: 4.3,
      installment: true,
    },
    {
      id: "25",
      name: "Xiaomi Watch S4 Sport",
      slug: "xiaomi-watch-s4-sport",
      image: "/placeholder.svg?height=300&width=300",
      price: 3790000,
      originalPrice: 4290000,
      discount: 12,
      rating: 4.4,
      installment: true,
    },
  ],
  audio: [
    {
      id: "26",
      name: "Tai nghe Apple AirPods 4 Chính Hãng",
      slug: "airpods-4",
      image: "/placeholder.svg?height=300&width=300",
      price: 3050000,
      originalPrice: 3490000,
      discount: 13,
      rating: 4.7,
      installment: false,
    },
    {
      id: "27",
      name: "Tai nghe Bluetooth TWS JBL Tour Pro 3",
      slug: "jbl-tour-pro-3",
      image: "/placeholder.svg?height=300&width=300",
      price: 929000,
      originalPrice: 1090000,
      discount: 15,
      rating: 4.4,
      installment: false,
    },
    {
      id: "28",
      name: "Tai nghe Bluetooth hifi",
      slug: "tai-nghe-bluetooth-hifi",
      image: "/placeholder.svg?height=300&width=300",
      price: 2590000,
      originalPrice: 2990000,
      discount: 13,
      rating: 4.3,
      installment: false,
    },
    {
      id: "29",
      name: "Tai nghe Bluetooth chính hãng",
      slug: "tai-nghe-bluetooth-chinh-hang",
      image: "/placeholder.svg?height=300&width=300",
      price: 450000,
      originalPrice: 550000,
      discount: 18,
      rating: 4.2,
      installment: false,
    },
    {
      id: "30",
      name: "Loa Bluetooth JBL Flip 6",
      slug: "jbl-flip-6",
      image: "/placeholder.svg?height=300&width=300",
      price: 3500000,
      originalPrice: 3990000,
      discount: 12,
      rating: 4.6,
      installment: false,
    },
  ],
}

// Category tabs configuration
export const categoryTabs = {
  phones: [
    { id: "all", label: "Sản phẩm bán chạy nhất" },
    { id: "iphone", label: "iPhone" },
    { id: "samsung", label: "Samsung" },
    { id: "xiaomi", label: "Xiaomi | OPPO" },
  ],
  tablets: [
    { id: "all", label: "Tất cả" },
    { id: "ipad", label: "iPad" },
    { id: "samsung-tab", label: "Samsung Tab" },
    { id: "other", label: "Khác" },
  ],
}

// Mock articles for news section
export const mockArticles: Article[] = [
  {
    id: "1",
    title: "Di Động Việt thông báo lịch nghỉ Tết Bính Ngọ 2026",
    slug: "di-dong-viet-thong-bao-lich-nghi-tet",
    image: "/placeholder.svg?height=200&width=350",
    author: "Hoàng Anh",
    date: "12/02/2026",
  },
  {
    id: "2",
    title: "Ưu đãi giảm thêm 200K khi thanh toán chuyển khoản",
    slug: "uu-dai-giam-them-200k",
    image: "/placeholder.svg?height=200&width=350",
    author: "Hoàng Anh",
    date: "10/02/2026",
  },
  {
    id: "3",
    title: "Di Động Việt ưu đãi mua iPhone tháng 02/2026",
    slug: "di-dong-viet-uu-dai-mua-iphone",
    image: "/placeholder.svg?height=200&width=350",
    author: "Hoàng Anh",
    date: "15/01/2026",
  },
  {
    id: "4",
    title: "Sale Sốc 30-31/01: Giảm Đến 500K Tại Di Động Việt TP HCM",
    slug: "sale-soc-30-31-01",
    image: "/placeholder.svg?height=200&width=350",
    author: "Hoàng Anh",
    date: "15/02/2026",
  },
  {
    id: "5",
    title: "Mở bán Redmi Note 15 Series tại Di Động Việt",
    slug: "mo-ban-redmi-note-15",
    image: "/placeholder.svg?height=200&width=350",
    author: "Hoàng Anh",
    date: "10/02/2026",
  },
  {
    id: "6",
    title: "Tết Đỏ Dủ Đầy: Combo ưu đãi lớn - Săm ngay đón Tết giảm đến 1 triệu đồng",
    slug: "tet-do-du-day-combo-uu-dai",
    image: "/placeholder.svg?height=200&width=350",
    author: "Hoàng Anh",
    date: "11/02/2026",
  },
]

// Hero slider data
export const heroSlides = [
  {
    id: "1",
    image: "/placeholder.svg?height=400&width=1000",
    href: "/khuyen-mai/tet",
    alt: "Tết đỏ dủ đầy",
  },
  {
    id: "2",
    image: "/placeholder.svg?height=400&width=1000",
    href: "/san-pham/iphone-17",
    alt: "iPhone 17 Pro Max",
  },
  {
    id: "3",
    image: "/placeholder.svg?height=400&width=1000",
    href: "/san-pham/samsung-galaxy-s25",
    alt: "Samsung Galaxy S25",
  },
]

// Side promos
export const sidePromos = [
  {
    id: "1",
    image: "/placeholder.svg?height=150&width=300",
    href: "/khuyen-mai/galaxy-s25",
    title: "Galaxy S25 5G",
    subtitle: "Đổi máy cũ, giảm thêm",
  },
  {
    id: "2",
    image: "/placeholder.svg?height=150&width=300",
    href: "/khuyen-mai/redmi-note-15",
    title: "REDMI Note 15",
    subtitle: "Bền vô đối",
  },
]
